version: 2
jobs:
  build:
    working_directory: ~/django-asset-definitions
    docker:
      - image: ubuntu:16.04
    steps:
      - run: apt-get update && apt-get install -y python2.7-dev python3.5-dev python-pip
      - run: pip install flake8 tox
      - checkout
      - run: flake8 ./src
      - run: tox
